### ISSUE TITLE
No data using DF_RawStreams

### ISSUE THREAD

**Issue by sepjansen** [BlazingForests/realsense_camera_tools#1]
Following instructions from tutorial I get the following after pressing 'Start' button:
Device connected
Streaming...
Stopped

No files are generated and no camera images are visible.
Running on Windows 8.1 64 bit. Camera images are visible in other Intel Realsense SDK apps.

Any ideas?

**Comment by BlazingForests** [comment]
hi, what is the version of your Realsense SDK?

**Comment by sepjansen** [comment]
I got Build Number: 5.0.3.187777 here:
https://software.intel.com/en-us/intel-realsense-sdk/download

**Comment by BlazingForests** [comment]
yeh, there have some problem with the 5.xx SDK version.
I use the 4.xx SDK version for now.
Maybe you can try 4.xx version first.

**Comment by sepjansen** [comment]
I tried version 4.xx of the SDK in combination with version 1.3.xx of the depth camera manager (Also tried 1.2.xx, but this didn't work for me).

I still get the same behavior (Device connecteed streaming..., stopped. No image visible and no files generated). Maybe the debug logs can help:

```
'DF_RawStreams_d.exe': Loaded 'C:\Program Files\Common Files\Intel\RSSDK\v4\bin\x64\libpxcpowermanager.dll', Cannot find or open the PDB file
'DF_RawStreams_d.exe': Loaded 'C:\Windows\System32\msxml3.dll', Cannot find or open the PDB file
'DF_RawStreams_d.exe': Loaded 'C:\Windows\System32\urlmon.dll', Cannot find or open the PDB file
'DF_RawStreams_d.exe': Loaded 'C:\Windows\System32\iertutil.dll', Cannot find or open the PDB file
'DF_RawStreams_d.exe': Loaded 'C:\Windows\System32\wininet.dll', Cannot find or open the PDB file
'DF_RawStreams_d.exe': Loaded 'C:\Windows\System32\userenv.dll', Cannot find or open the PDB file
First-chance exception at 0x00007ffc99ab8b9c in DF_RawStreams_d.exe: 0xE0000001: 0xe0000001.
First-chance exception at 0x00007ffc99ab8b9c in DF_RawStreams_d.exe: 0xE0000001: 0xe0000001.
'DF_RawStreams_d.exe': Loaded 'C:\Windows\System32\wintrust.dll', Cannot find or open the PDB file
'DF_RawStreams_d.exe': Loaded 'C:\Windows\System32\crypt32.dll', Cannot find or open the PDB file
'DF_RawStreams_d.exe': Loaded 'C:\Windows\System32\msasn1.dll', Cannot find or open the PDB file
The thread 'Win64 Thread' (0x1298) has exited with code 0 (0x0).
The thread 'Win64 Thread' (0x1624) has exited with code 0 (0x0).
```

**Comment by sthoduka** [comment]
Are you able to view the depth/rgb stream using any of the other sample apps? I've had issues with certain computers where the camera disconnects as soon as I try to access the depth stream. This is possibly because the USB port doesn't provide enough power. You could also try an externally powered USB hub if this is the case.

**Comment by sepjansen** [comment]
Ok, I've got it working.
Power supply was indeed the problem. USB 3.0 port with 100 mA should be enough, but on some hardware I found it was not. External hub did not work for me. See also discussion here:
https://software.intel.com/en-us/forums/topic/542101.

In the end I switched to another laptop.

I installed the 4.xx version of the SDK and the 1.2.xx version of the depth camera manager.

Maybe you can illuminate some of the process happening in the app:
1. Are there requirements for image used in the Raw Streams app? e.g.  should the image be static?
2. What exactly is stored in the bin file? With 2.4 MB per file and 2047 files, this seems a lot of data.

Maybe it's good to update the readme with some of these questions and installation instructions for the SDK, etc. I'd be happy to do this.

**Comment by BlazingForests** [comment]
thank you.

If you happy to do this, you can fork this repo, and modify README.md file, then create a pull request. I will merge it.

I will write some detail about the uvmap file.

**Comment by sepjansen** [comment]
Since Readme is now updated, I'll close the issue.
